In [2]:
import tensorflow as tf
from numpy.random import RandomState

#### 1. 定义神经网络的参数，输入和输出节点。

In [3]:
batch_size = 8
w1= tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2= tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))
x = tf.placeholder(tf.float32, shape=(None, 2), name="x-input")
y_= tf.placeholder(tf.float32, shape=(None, 1), name='y-input')

#### 2. 定义前向传播过程，损失函数及反向传播算法。

In [14]:
a = tf.matmul(x, w1)
xW1_plus_W2 = tf.matmul(a, w2)
y = tf.sigmoid(xW1_plus_W2)
cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0))
                                + (1 - y_) * tf.log(tf.clip_by_value(1 - y, 1e-10, 1.0)))
train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

####  3. 生成模拟数据集。

In [15]:
rdm = RandomState(1)
X = rdm.rand(128, 2)
Y = [[int(x1+x2 < 1)] for (x1, x2) in X]    

#### 4. 创建一个会话来运行TensorFlow程序。

In [16]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    
    # 输出目前（未经训练）的参数取值。
    print(sess.run(w1))
    print(sess.run(w2))
    print("\n")
    
    # 训练模型。
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % 128
        end = (i*batch_size) % 128 + batch_size
        # print("{0}th training step(s), the length of this batch is {1}".format(i, X[start:end].shape[0]))
        sess.run([train_step, y, y_], feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            total_cross_entropy = sess.run(cross_entropy, feed_dict={x: X, y_: Y})
            print("After %d training step(s), cross entropy on all data is %g" % (i, total_cross_entropy))
            out = sess.run(y, feed_dict={x: X})
            print(out)
            # print("real out:{0}".format())
    
    # 输出训练后的参数取值。
    print("\n")
    print(sess.run(w1))
    print(sess.run(w2))

[[-0.81131822  1.48459876  0.06532937]
 [-2.4427042   0.0992484   0.59122431]]
[[-0.81131822]
 [ 1.48459876]
 [ 0.06532937]]


After 0 training step(s), cross entropy on all data is 1.89805
[[ 0.93996924]
 [ 0.65792418]
 [ 0.65013927]
 [ 0.78249145]
 [ 0.90892285]
 [ 0.93591416]
 [ 0.92300171]
 [ 0.82173133]
 [ 0.91700244]
 [ 0.69637913]
 [ 0.98769349]
 [ 0.9163658 ]
 [ 0.98836994]
 [ 0.581231  ]
 [ 0.91566247]
 [ 0.76709974]
 [ 0.98004591]
 [ 0.93476278]
 [ 0.97745287]
 [ 0.84215701]
 [ 0.9884299 ]
 [ 0.92478633]
 [ 0.77969486]
 [ 0.96213448]
 [ 0.75114346]
 [ 0.82101834]
 [ 0.76491719]
 [ 0.82085901]
 [ 0.87656438]
 [ 0.96081787]
 [ 0.76641369]
 [ 0.94699067]
 [ 0.78612429]
 [ 0.95315784]
 [ 0.9815045 ]
 [ 0.94698125]
 [ 0.89514387]
 [ 0.8169207 ]
 [ 0.96790189]
 [ 0.97630489]
 [ 0.97969592]
 [ 0.94801819]
 [ 0.93759352]
 [ 0.96481723]
 [ 0.96241838]
 [ 0.91540188]
 [ 0.92677748]
 [ 0.84297526]
 [ 0.97866344]
 [ 0.79292685]
 [ 0.88839495]
 [ 0.96469969]
 [ 0.98107094]
 [ 0.88645059]


After 1000 training step(s), cross entropy on all data is 0.655075
[[ 0.35005265]
 [ 0.42648584]
 [ 0.48503754]
 [ 0.42562163]
 [ 0.39050514]
 [ 0.35802227]
 [ 0.30624238]
 [ 0.34271547]
 [ 0.38689613]
 [ 0.45888728]
 [ 0.31395105]
 [ 0.35138044]
 [ 0.33319527]
 [ 0.49486768]
 [ 0.30470526]
 [ 0.40321347]
 [ 0.42003515]
 [ 0.4588801 ]
 [ 0.33746752]
 [ 0.32493544]
 [ 0.37125689]
 [ 0.32852727]
 [ 0.39715803]
 [ 0.47547081]
 [ 0.48315969]
 [ 0.34049523]
 [ 0.44619691]
 [ 0.51255572]
 [ 0.49399221]
 [ 0.36291677]
 [ 0.40507758]
 [ 0.43511865]
 [ 0.37410253]
 [ 0.40949443]
 [ 0.40667856]
 [ 0.51342362]
 [ 0.31820339]
 [ 0.48024058]
 [ 0.46323901]
 [ 0.36476213]
 [ 0.39487576]
 [ 0.45382139]
 [ 0.30544519]
 [ 0.29815963]
 [ 0.38443181]
 [ 0.28774017]
 [ 0.38393492]
 [ 0.46328548]
 [ 0.40764889]
 [ 0.35340995]
 [ 0.38976684]
 [ 0.45877123]
 [ 0.39620683]
 [ 0.28753856]
 [ 0.30299103]
 [ 0.47541368]
 [ 0.38030538]
 [ 0.32597581]
 [ 0.3214398 ]
 [ 0.50665665]
 [ 0.49461633]
 [ 0.44143611]
 [ 

After 2000 training step(s), cross entropy on all data is 0.626172
[[ 0.2978695 ]
 [ 0.43122044]
 [ 0.46152636]
 [ 0.40015918]
 [ 0.33589089]
 [ 0.30441689]
 [ 0.28883451]
 [ 0.34821689]
 [ 0.32968646]
 [ 0.43831232]
 [ 0.21983989]
 [ 0.31374785]
 [ 0.22529653]
 [ 0.48097852]
 [ 0.29221678]
 [ 0.39358959]
 [ 0.2803342 ]
 [ 0.35040316]
 [ 0.25161472]
 [ 0.33280611]
 [ 0.23969342]
 [ 0.29822233]
 [ 0.38720185]
 [ 0.33179602]
 [ 0.436436  ]
 [ 0.34734243]
 [ 0.41494009]
 [ 0.42992204]
 [ 0.39967167]
 [ 0.28487593]
 [ 0.39467946]
 [ 0.32986349]
 [ 0.37416691]
 [ 0.31292331]
 [ 0.27182582]
 [ 0.36478743]
 [ 0.30888015]
 [ 0.41577426]
 [ 0.3189435 ]
 [ 0.26481679]
 [ 0.27085778]
 [ 0.33718449]
 [ 0.27920741]
 [ 0.25225931]
 [ 0.29232609]
 [ 0.28417939]
 [ 0.32232296]
 [ 0.39873615]
 [ 0.2780754 ]
 [ 0.36206159]
 [ 0.34578651]
 [ 0.32134339]
 [ 0.26855558]
 [ 0.29765025]
 [ 0.22424929]
 [ 0.44834515]
 [ 0.25338453]
 [ 0.32672489]
 [ 0.23095343]
 [ 0.3890073 ]
 [ 0.49164212]
 [ 0.4405652 ]
 [ 

After 3000 training step(s), cross entropy on all data is 0.615096
[[ 0.31044212]
 [ 0.45548376]
 [ 0.45369956]
 [ 0.40841749]
 [ 0.33786669]
 [ 0.31447572]
 [ 0.33157024]
 [ 0.39646935]
 [ 0.33116734]
 [ 0.4396804 ]
 [ 0.21627161]
 [ 0.33428127]
 [ 0.21220221]
 [ 0.47524509]
 [ 0.33846414]
 [ 0.41666424]
 [ 0.23662689]
 [ 0.3089729 ]
 [ 0.24852507]
 [ 0.38720271]
 [ 0.20984653]
 [ 0.32813874]
 [ 0.41176972]
 [ 0.27174261]
 [ 0.41724706]
 [ 0.39700398]
 [ 0.41435948]
 [ 0.38436007]
 [ 0.35434327]
 [ 0.28090453]
 [ 0.41680914]
 [ 0.29620978]
 [ 0.41072857]
 [ 0.28956825]
 [ 0.23310091]
 [ 0.29131582]
 [ 0.35409984]
 [ 0.38859716]
 [ 0.26217929]
 [ 0.24976002]
 [ 0.23903395]
 [ 0.29370713]
 [ 0.31645092]
 [ 0.27842984]
 [ 0.27683756]
 [ 0.34006706]
 [ 0.32219651]
 [ 0.3763974 ]
 [ 0.24114215]
 [ 0.4093138 ]
 [ 0.35361907]
 [ 0.26833028]
 [ 0.23498754]
 [ 0.3629235 ]
 [ 0.23033009]
 [ 0.44150606]
 [ 0.22352692]
 [ 0.37639186]
 [ 0.22812706]
 [ 0.32968202]
 [ 0.49168891]
 [ 0.45744678]
 [ 

After 4000 training step(s), cross entropy on all data is 0.610309
[[ 0.32029057]
 [ 0.47344002]
 [ 0.4481414 ]
 [ 0.41473064]
 [ 0.33974713]
 [ 0.32241252]
 [ 0.36509812]
 [ 0.43331987]
 [ 0.33270043]
 [ 0.44085118]
 [ 0.21432389]
 [ 0.35011417]
 [ 0.20362818]
 [ 0.47114125]
 [ 0.37475944]
 [ 0.43396285]
 [ 0.20843177]
 [ 0.28102416]
 [ 0.24688388]
 [ 0.42912775]
 [ 0.19046073]
 [ 0.35135213]
 [ 0.4302201 ]
 [ 0.23304024]
 [ 0.40364513]
 [ 0.43495733]
 [ 0.41417933]
 [ 0.35264668]
 [ 0.32320675]
 [ 0.27857733]
 [ 0.4333984 ]
 [ 0.27347413]
 [ 0.43829843]
 [ 0.27372739]
 [ 0.20796466]
 [ 0.24413246]
 [ 0.38926357]
 [ 0.36950967]
 [ 0.22567515]
 [ 0.2397304 ]
 [ 0.21808168]
 [ 0.26466778]
 [ 0.3457087 ]
 [ 0.29910031]
 [ 0.26641491]
 [ 0.38439173]
 [ 0.32257453]
 [ 0.36076987]
 [ 0.21697915]
 [ 0.44516465]
 [ 0.35978073]
 [ 0.23389342]
 [ 0.21299201]
 [ 0.41448912]
 [ 0.23546283]
 [ 0.43670192]
 [ 0.20398018]
 [ 0.41473711]
 [ 0.22670014]
 [ 0.28992757]
 [ 0.49174708]
 [ 0.46993956]
 [ 



[[ 0.02476984  0.5694868   1.69219422]
 [-2.19773483 -0.23668921  1.11438966]]
[[-0.45544702]
 [ 0.49110931]
 [-0.9811033 ]]
